[tools]
node = "22"

[tasks.crossbuild]
run = "cross build --release --features vendored-openssl --target arm-unknown-linux-gnueabihf"

[tasks.build]
sources = [
  "packages/**/*.rs",
  "packages/cli/resources/**/*",
  "packages/cli/templates/*.html",
]
outputs = ["target/debug/flick-sync"]

[tasks.serve]
run = "cargo run -- serve -p 3000"
