/*
 Generated by typeshare 1.3.0
*/

export interface CollectionState {
	id: string;
	library: number;
	title: string;
	items?: string[];
	lastUpdated: number;
	thumbnail?: ThumbnailState;
}

export interface PlaylistState {
	id: string;
	title: string;
	videos?: string[];
}

export interface LibraryState {
	id: number;
	title: string;
	type: LibraryType;
}

export interface SeasonState {
	id: string;
	show: string;
	index: number;
	title: string;
}

export interface ShowState {
	id: string;
	library: number;
	title: string;
	year: number;
	lastUpdated: number;
	thumbnail?: ThumbnailState;
}

export interface MovieState {
	library: number;
	year: number;
}

export interface EpisodeState {
	season: string;
	index: number;
}

export interface VideoPartState {
	duration: number;
	download?: DownloadState;
}

export interface VideoState {
	id: string;
	title: string;
	detail: VideoDetail;
	airDate: string;
	thumbnail?: ThumbnailState;
	mediaId: number;
	lastUpdated: number;
	parts: VideoPartState[];
	transcodeProfile?: string;
	playPosition?: number;
}

export interface ServerState {
	token?: string;
	name: string;
	playlists?: PlaylistState[];
	collections?: CollectionState[];
	libraries?: LibraryState[];
	shows?: ShowState[];
	seasons?: SeasonState[];
	videos?: VideoState[];
}

export interface State {
	clientId: string;
	servers?: Record<string, ServerState>;
}

