[package]
name = "dlna-server"
version = "0.1.0"
edition = "2024"

[features]
default = ["rt-tokio"]
rt-tokio = ["tokio/rt"]
rt-async = ["dep:async-std"]

[dependencies]
tokio = { version = "1.43.0", features = ["net", "signal"] }
tokio-util = { version = "0.7.13", features = ["net", "codec"] }
anyhow = "1.0.96"
actix-web = { version = "4.9.0", default-features = false, features = [
  "macros",
  "compat",
] }
async-std = { version = "1.13.0", optional = true }
http = "1.2.0"
tracing = "0.1.41"
futures = "0.3.31"
bytes = "1.10.0"
uuid = { version = "1.15.1", features = ["v4"] }
getifaddrs = "0.1.5"
socket2 = "0.5.8"
xml = "0.8.20"
mime = "0.3.17"
serde = { version = "1.0.218", features = ["derive"] }
thiserror = "1.0.40"
serde_with = "3.12.0"
async-trait = "0.1.87"
url = "2.5.2"
socket-pktinfo = "0.2.1"
gethostname = "1.0.0"
tokio-stream = { version = "0.1.17", features = ["signal"] }
