[package]
name = "dlna-server"
version = "0.1.0"
edition = "2024"

[features]
default = ["rt-tokio"]
rt-tokio = ["tokio/rt"]
rt-async = ["dep:async-std"]

[dependencies]
tokio = { version = "1.43.0", features = ["net"] }
tokio-util = { version = "0.7.13", features = ["net", "codec"] }
anyhow = "1.0.96"
actix-web = "4.9.0"
async-std = { version = "1.13.0", optional = true }
http = "1.2.0"
tracing = "0.1.41"
futures = "0.3.31"
bytes = "1.10.0"
uuid = "1.15.1"
getifaddrs = "0.1.5"
socket2 = "0.5.8"
xml = "0.8.20"
mime = "0.3.17"
serde = "1.0.218"
thiserror = "1.0.40"
serde_with = "3.12.0"
async-trait = "0.1.87"
