[package]
name = "flick-sync"
version = "2.0.0"
edition = "2024"

[dependencies]
plex-api = { git = "https://github.com/Mossop/plex-api.rs.git", branch = "downloadqueue" }
thiserror = "2.0.12"
tracing = { version = "^0.1.37", features = ["attributes"] }
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
uuid = { version = "1.3.0", features = ["v4"] }
async-recursion = "1.0.4"
time = { version = "0.3.20", features = ["serde", "serde-well-known"] }
typeshare = "1.0.1"
futures = "0.3.28"
pin-project = "1.0.12"
lazy_static = "1.4.0"
serde_plain = "1.0.1"
tokio = { version = "1.29.1", features = [
  "sync",
  "fs",
  "io-util",
  "time",
  "process",
] }
xml = "0.8.20"
tempfile = "3.17.1"
pathdiff = "0.2.3"
tokio-util = "0.7.13"
scoped-futures = "0.1.4"
mime = "0.3.17"
file-format = { version = "0.27.0", features = [
  "reader-asf",
  "reader-ebml",
  "reader-mp4",
  "reader-rm",
  "reader-id3v2",
] }
anyhow = "1.0.97"
