[package]
name = "flick-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
plex-api = { git = "https://github.com/Mossop/plex-api.rs.git", branch = "field_fixes" }
thiserror = "1.0.40"
tracing = { version = "^0.1.37", features = ["attributes"] }
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
tokio = {version = "1.27.0", features = ["full"] }
uuid = { version = "1.3.0", features = ["v4"] }
async-recursion = "1.0.4"
time = { version = "0.3.20", features = ["serde", "serde-well-known"] }
async-trait = "0.1.68"
async-std = "1.12.0"
typeshare = "1.0.1"
futures = "0.3.28"
pin-project = "1.0.12"
lazy_static = "1.4.0"
