[package]
name = "flick-sync-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "flick-sync"
path = "src/main.rs"

[dependencies]
futures = "0.3.28"
flick-sync = { path = "../flick-sync" }
clap = { version = "4.1.13", features = ["derive", "env"] }
tokio = { version = "1.26.0", features = ["full"] }
console = "0.15.5"
dialoguer = "0.10.3"
indicatif = "0.17.3"
tracing = { version = "^0.1.37", features = ["attributes"] }
async-trait = "0.1.68"
thiserror = "1.0.40"
url = "2.3.1"
tracing-subscriber = {version = "0.3.16", features = ["env-filter"] }
enum_dispatch = "0.3.11"
