[package]
name = "flick-sync-cli"
version = "1.6.0"
edition = "2024"

[features]
vendored-openssl = ["dep:openssl"]

[[bin]]
name = "flick-sync"
path = "src/main.rs"

[dependencies]
futures = "0.3.28"
flick-sync = { path = "../flick-sync" }
dlna-server = { path = "../dlna-server" }
clap = { version = "4.1.13", features = ["derive", "env"] }
console = "0.15.5"
dialoguer = "0.11.0"
indicatif = "0.17.3"
tracing = { version = "0.1.37", features = ["attributes"] }
thiserror = "2.0.11"
url = "2.3.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
enum_dispatch = "0.3.11"
tokio = { version = "1.29.1", features = [
  "rt",
  "macros",
  "rt-multi-thread",
  "signal",
] }
anyhow = "1.0.96"
async-trait = "0.1.87"
mime = "0.3.17"
bytes = "1.10.0"
tokio-util = "0.7.13"
file-format = { version = "0.26.0", features = [
  "reader-asf",
  "reader-ebml",
  "reader-mp4",
  "reader-rm",
  "reader-id3v2",
] }
image = "0.25.5"
pathdiff = "0.2.3"
pin-project = "1.1.10"
rust-embed = "8.6.0"
openssl = { version = "0.10", features = ["vendored"], optional = true }
tokio-stream = { version = "0.1.17", features = ["signal"] }
actix-web = { version = "4.9.0", default-features = false, features = [
  "macros",
  "compat",
] }
rinja = "0.3.5"
