[package]
name = "flick-sync-cli"
version = "2.0.0"
edition = "2024"

[features]
vendored-openssl = ["dep:openssl"]

[[bin]]
name = "flick-sync"
path = "src/main.rs"

[dependencies]
futures = "0.3.28"
flick-sync = { path = "../flick-sync" }
dlna-server = { path = "../dlna-server" }
clap = { version = "4.1.13", features = ["derive", "env"] }
console = "0.15.11"
dialoguer = "0.11.0"
indicatif = "0.17.11"
tracing = { version = "0.1.37", features = ["attributes"] }
thiserror = "2.0.11"
url = "2.3.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
enum_dispatch = "0.3.11"
tokio = { version = "1.29.1", features = [
  "rt",
  "macros",
  "rt-multi-thread",
  "signal",
] }
anyhow = "1.0.96"
async-trait = "0.1.87"
mime = "0.3.17"
bytes = "1.10.0"
tokio-util = "0.7.13"
image = "0.25.5"
pin-project = "1.1.10"
rust-embed = "8.6.0"
openssl = { version = "0.10", features = ["vendored"], optional = true }
tokio-stream = { version = "0.1.17", features = ["signal", "sync"] }
actix-web = { version = "4.9.0", default-features = false, features = [
  "macros",
  "compat",
  "rustls-0_23",
] }
actix-tls = "3.4.0"
askama = { version = "0.14.0", features = ["serde_json"] }
regex = "1.11.1"
lazy_static = "1.4.0"
time = "0.3.20"
serde = { version = "1.0.158", features = ["derive"] }
rustls = { version = "0.23.25", default-features = false, features = [
  "ring",
  "logging",
  "std",
  "tls12",
] }
sysinfo = "0.35.2"
