[package]
name = "flick-sync-webserver"
version = "1.6.0"
edition = "2024"

[dependencies]
flick-sync = { path = "../flick-sync" }
actix-web = { version = "4.9.0", default-features = false, features = [
  "macros",
  "compat",
] }
askama = "0.12.1"
tokio = { version = "1.29.1", features = ["rt"] }
thiserror = "2.0.11"
