name: Android Builds

on:
  workflow_dispatch: {}

jobs:
  release-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: packages/mobile/package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./packages/mobile
        run: npm install

      - name: Build
        working-directory: ./packages/mobile
        run: eas build --profile preview --platform android --non-interactive

      - name: Download build
        working-directory: ./packages/mobile
        run: |
          curl -o flick-sync-android.apk `eas build:list --non-interactive --git-commit-hash ${GITHUB_SHA} -p android --distribution internal --status=finished --json 2>/dev/null | jq -r '.[0].artifacts.applicationArchiveUrl'`

      - name: Upload build artifact
        uses: actions/upload-artifact@v4

        with:
          name: flick-sync-android.apk
          path: flick-sync-android.apk
