name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            host: x86_64-unknown-linux-gnu
            target: x86_64-unknown-linux-gnu
            artifact: flick-sync-linux-x64.tar.bz2
          - runner: macos-latest
            host: aarch64-apple-darwin
            target: aarch64-apple-darwin
            artifact: flick-sync-mac.tar.bz2
          - runner: ubuntu-latest
            host: x86_64-unknown-linux-gnu
            target: arm-unknown-linux-gnueabihf
            artifact: flick-sync-linux-armhf.tar.bz2
          - runner: ubuntu-latest
            host: x86_64-unknown-linux-gnu
            target: aarch64-unknown-linux-gnu
            artifact: flick-sync-linux-arm64.tar.bz2

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup
            target/
          key: ${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Install cross
        if: ${{ matrix.target != matrix.host }}
        run: |
          cargo install cross --git https://github.com/cross-rs/cross || true

      - name: Cross compile
        if: ${{ matrix.target != matrix.host }}
        run: cross build --release --features vendored-openssl --target ${{ matrix.target }}

      - name: Build
        if: ${{ matrix.target == matrix.host }}
        run: cargo build --release --features vendored-openssl --target-dir target/${{ matrix.target }}

      - name: Compress
        run: tar -cjf ${{ matrix.artifact }} -C target/${{ matrix.target }}/release flick-sync

      - name: Upload build artifact
        uses: actions/upload-artifact@v4

        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: packages/mobile/package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: ./packages/mobile
        run: npm install

      - name: Build
        working-directory: ./packages/mobile
        run: eas build --profile preview --platform android --non-interactive

      - name: Download build
        working-directory: ./packages/mobile
        run: |
          curl -L -o flick-sync-android.apk `cd packages/mobile && eas build:list --non-interactive --git-commit-hash ${GITHUB_SHA} -p android -e preview --status=finished --json 2>/dev/null | jq -r '.[0].artifacts.applicationArchiveUrl'`

      - name: Upload build artifact
        uses: actions/upload-artifact@v4

        with:
          name: flick-sync-android.apk
          path: flick-sync-android.apk

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name: Release
    needs:
      - build
      - build-android
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

        with:
          path: artifacts
          merge-multiple: true

      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: artifacts/*
          tag: ${{ github.ref }}
