name: Release Builds

on:
  push:
    tags:
      - 'v*'

jobs:
  build-cli:
    name: Release ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-20.04
            name: Linux
            artifact: flick-sync-linux.tar.bz2
          - runner: macos-12
            name: macOS
            artifact: flick-sync-mac.tar.bz2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Compress
        run: tar -cjf ${{ matrix.artifact }} -C target/release flick-sync

      - name: Upload build artifact
        uses: actions/upload-artifact@v3

        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

  release-cli:
    needs: [build-cli]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

        with:
          path: artifacts

      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: artifacts/*/*.tar.bz2
          tag: ${{ github.ref }}
